"""add name column to campaign

Revision ID: 8e92b6a4fcd6
Revises: 8d4e569d38a0
Create Date: 2025-03-04 17:45:44.810058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e92b6a4fcd6'
down_revision = '8d4e569d38a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
